name: Legacy JS Linter

on: 
  pull_request:
    branches: 
      - master
    paths:
      - 'src/**'
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Get file changes
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.3
    - name: Filter file changes
      id: filter_file_changes
      uses: actions/github-script@0.9.0
      with:
        script: |
          const RELEVANT_FILE_TYPE = /^src\/.*\.(js|jsx)$/
          let relevantFiles = ""
          const changedFiles = ${{ steps.get_file_changes.outputs.files }}
          changedFiles.forEach(f => {
            if (f.match(RELEVANT_FILE_TYPE)) {
              relevantFiles += " " + f
            }
          })
          if (relevantFiles) {
            return "yarn install && yarn lint" + relevantFiles + " --max-warnings=0"
          }
          return ':'
    - name: Legacy JS Linter
      run: |
        eval ${{ steps.filter_file_changes.outputs.result }}
