name: Legacy JS Linter

on: 
  pull_request:
    branches: 
      - master
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Lint Changed Legacy JS Files
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        echo $URL
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename' | grep -E '^src\/.*\.(js|jsx)$')
        echo "FILES: " $FILES
        yarn install && yarn lint $FILES --max-warnings=0
