name: Legacy JS Linter

on: 
  pull_request:
    branches: 
      - master
    paths:
      - 'src/**'
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Get file changes
      id: get_file_changes
      run: |
        URL="https://api.github.com/repos/brandonday7/fizz-buzz/pulls/8/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename' | grep -E '^src\/.*\.(js|jsx)$')
        yarn install && yarn lint $FILES --max-warnings=0
        echo $FILES
    # - name: Filter file changes
    #   id: filter_file_changes
    #   uses: actions/github-script@0.9.0
    #   with:
    #     script: |
    #       console.log(${{ steps.get_file_changes.outputs }})
    #       const RELEVANT_FILE_TYPE = /^src\/.*\.(js|jsx)$/
    #       const changedFiles = ${{ steps.get_file_changes.outputs.files }}
    #       const relevantFiles = changedFiles.filter(f => f.match(RELEVANT_FILE_TYPE)).join(' ')

    #       if (relevantFiles) {
    #         return "yarn install && yarn lint " + relevantFiles + " --max-warnings=0"
    #       }
    #       return ':'
    # - name: Legacy JS Linter
    #   run: |
    #     eval ${{ steps.filter_file_changes.outputs.result }}
