name: Legacy JS Linter

on: 
  pull_request:
    branches: 
      - master
    paths:
      - 'src/**'
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Get file changes
      id: get_file_changes
      uses: futuratrepadeira/changed-files@v3.1.0
      with:
        repo-token: ${{ github.token }}
    - name: Filter file changes
      id: filter_file_changes
      uses: actions/github-script@0.9.0
      with:
        script: |
          console.log(${{ steps.get_file_changes.outputs }})
          const RELEVANT_FILE_TYPE = /^src\/.*\.(js|jsx)$/
          const changedFiles = ${{ steps.get_file_changes.outputs.files }}
          const relevantFiles = changedFiles.filter(f => f.match(RELEVANT_FILE_TYPE)).join(' ')

          if (relevantFiles) {
            return "yarn install && yarn lint " + relevantFiles + " --max-warnings=0"
          }
          return ':'
    - name: Legacy JS Linter
      run: |
        eval ${{ steps.filter_file_changes.outputs.result }}
