name: Legacy JS Linter

on: 
  pull_request:
    branches: 
      - master
    paths:
    - 'src/**'
  push:
    branches:
      - master
    paths:
    - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 10.x
    - name: Get file changes
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Filter file changes
      id: filter_file_changes
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const RELEVANT_FILE_TYPE = /^src\/.*\.(js|jsx|ts|tsx)$/
          let relevantFiles = ""
          const changedFiles = ${{ steps.get_file_changes.outputs.files }}
          changedFiles.forEach(f => {
            if (f.match(RELEVANT_FILE_TYPE)) {
              relevantFiles += " " + f
            }
          })
          if (relevantFiles) {
            return "yarn install && yarn lint" + relevantFiles + " --max-warnings=0"
          }
          return ':'
    - name: Legacy JS Linter
      run: |
        eval ${{ steps.filter_file_changes.outputs.result }}
